// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameHeartbeat.proto

#ifndef PROTOBUF_INCLUDED_GameHeartbeat_2eproto
#define PROTOBUF_INCLUDED_GameHeartbeat_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_GameHeartbeat_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_GameHeartbeat_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_GameHeartbeat_2eproto();
namespace zl {
namespace proto {
class GameHeartBeat;
class GameHeartBeatDefaultTypeInternal;
extern GameHeartBeatDefaultTypeInternal _GameHeartBeat_default_instance_;
}  // namespace proto
}  // namespace zl
namespace google {
namespace protobuf {
template<> ::zl::proto::GameHeartBeat* Arena::CreateMaybeMessage<::zl::proto::GameHeartBeat>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace zl {
namespace proto {

// ===================================================================

class GameHeartBeat final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zl.proto.GameHeartBeat) */ {
 public:
  GameHeartBeat();
  virtual ~GameHeartBeat();

  GameHeartBeat(const GameHeartBeat& from);

  inline GameHeartBeat& operator=(const GameHeartBeat& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GameHeartBeat(GameHeartBeat&& from) noexcept
    : GameHeartBeat() {
    *this = ::std::move(from);
  }

  inline GameHeartBeat& operator=(GameHeartBeat&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GameHeartBeat& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GameHeartBeat* internal_default_instance() {
    return reinterpret_cast<const GameHeartBeat*>(
               &_GameHeartBeat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(GameHeartBeat* other);
  friend void swap(GameHeartBeat& a, GameHeartBeat& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GameHeartBeat* New() const final {
    return CreateMaybeMessage<GameHeartBeat>(nullptr);
  }

  GameHeartBeat* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GameHeartBeat>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GameHeartBeat& from);
  void MergeFrom(const GameHeartBeat& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameHeartBeat* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 FPS = 1;
  void clear_fps();
  static const int kFPSFieldNumber = 1;
  ::google::protobuf::int32 fps() const;
  void set_fps(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:zl.proto.GameHeartBeat)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 fps_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_GameHeartbeat_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GameHeartBeat

// int32 FPS = 1;
inline void GameHeartBeat::clear_fps() {
  fps_ = 0;
}
inline ::google::protobuf::int32 GameHeartBeat::fps() const {
  // @@protoc_insertion_point(field_get:zl.proto.GameHeartBeat.FPS)
  return fps_;
}
inline void GameHeartBeat::set_fps(::google::protobuf::int32 value) {
  
  fps_ = value;
  // @@protoc_insertion_point(field_set:zl.proto.GameHeartBeat.FPS)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace zl

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_GameHeartbeat_2eproto
