// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProfileMaps.proto

#ifndef PROTOBUF_INCLUDED_ProfileMaps_2eproto
#define PROTOBUF_INCLUDED_ProfileMaps_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ProfileMaps_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_ProfileMaps_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_ProfileMaps_2eproto();
namespace zl {
namespace proto {
class ProfileMaps;
class ProfileMapsDefaultTypeInternal;
extern ProfileMapsDefaultTypeInternal _ProfileMaps_default_instance_;
class ProfileMaps_IdsByClientIpEntry_DoNotUse;
class ProfileMaps_IdsByClientIpEntry_DoNotUseDefaultTypeInternal;
extern ProfileMaps_IdsByClientIpEntry_DoNotUseDefaultTypeInternal _ProfileMaps_IdsByClientIpEntry_DoNotUse_default_instance_;
}  // namespace proto
}  // namespace zl
namespace google {
namespace protobuf {
template<> ::zl::proto::ProfileMaps* Arena::CreateMaybeMessage<::zl::proto::ProfileMaps>(Arena*);
template<> ::zl::proto::ProfileMaps_IdsByClientIpEntry_DoNotUse* Arena::CreateMaybeMessage<::zl::proto::ProfileMaps_IdsByClientIpEntry_DoNotUse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace zl {
namespace proto {

// ===================================================================

class ProfileMaps_IdsByClientIpEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<ProfileMaps_IdsByClientIpEntry_DoNotUse, 
    ::std::string, ::google::protobuf::int32,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
    0 > {
public:
#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
static bool _ParseMap(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  typedef ::google::protobuf::internal::MapEntry<ProfileMaps_IdsByClientIpEntry_DoNotUse, 
    ::std::string, ::google::protobuf::int32,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
    0 > SuperType;
  ProfileMaps_IdsByClientIpEntry_DoNotUse();
  ProfileMaps_IdsByClientIpEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const ProfileMaps_IdsByClientIpEntry_DoNotUse& other);
  static const ProfileMaps_IdsByClientIpEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const ProfileMaps_IdsByClientIpEntry_DoNotUse*>(&_ProfileMaps_IdsByClientIpEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class ProfileMaps final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zl.proto.ProfileMaps) */ {
 public:
  ProfileMaps();
  virtual ~ProfileMaps();

  ProfileMaps(const ProfileMaps& from);

  inline ProfileMaps& operator=(const ProfileMaps& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ProfileMaps(ProfileMaps&& from) noexcept
    : ProfileMaps() {
    *this = ::std::move(from);
  }

  inline ProfileMaps& operator=(ProfileMaps&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ProfileMaps& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ProfileMaps* internal_default_instance() {
    return reinterpret_cast<const ProfileMaps*>(
               &_ProfileMaps_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ProfileMaps* other);
  friend void swap(ProfileMaps& a, ProfileMaps& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ProfileMaps* New() const final {
    return CreateMaybeMessage<ProfileMaps>(nullptr);
  }

  ProfileMaps* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ProfileMaps>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ProfileMaps& from);
  void MergeFrom(const ProfileMaps& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProfileMaps* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, int32> IdsByClientIp = 1;
  int idsbyclientip_size() const;
  void clear_idsbyclientip();
  static const int kIdsByClientIpFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::google::protobuf::int32 >&
      idsbyclientip() const;
  ::google::protobuf::Map< ::std::string, ::google::protobuf::int32 >*
      mutable_idsbyclientip();

  // @@protoc_insertion_point(class_scope:zl.proto.ProfileMaps)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      ProfileMaps_IdsByClientIpEntry_DoNotUse,
      ::std::string, ::google::protobuf::int32,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      0 > idsbyclientip_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ProfileMaps_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ProfileMaps

// map<string, int32> IdsByClientIp = 1;
inline int ProfileMaps::idsbyclientip_size() const {
  return idsbyclientip_.size();
}
inline void ProfileMaps::clear_idsbyclientip() {
  idsbyclientip_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::google::protobuf::int32 >&
ProfileMaps::idsbyclientip() const {
  // @@protoc_insertion_point(field_map:zl.proto.ProfileMaps.IdsByClientIp)
  return idsbyclientip_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::google::protobuf::int32 >*
ProfileMaps::mutable_idsbyclientip() {
  // @@protoc_insertion_point(field_mutable_map:zl.proto.ProfileMaps.IdsByClientIp)
  return idsbyclientip_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace zl

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_ProfileMaps_2eproto
