// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Site.proto

#ifndef PROTOBUF_INCLUDED_Site_2eproto
#define PROTOBUF_INCLUDED_Site_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "EContentMap.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Site_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_Site_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_Site_2eproto();
namespace zl {
namespace proto {
class Site;
class SiteDefaultTypeInternal;
extern SiteDefaultTypeInternal _Site_default_instance_;
}  // namespace proto
}  // namespace zl
namespace google {
namespace protobuf {
template<> ::zl::proto::Site* Arena::CreateMaybeMessage<::zl::proto::Site>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace zl {
namespace proto {

// ===================================================================

class Site final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zl.proto.Site) */ {
 public:
  Site();
  virtual ~Site();

  Site(const Site& from);

  inline Site& operator=(const Site& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Site(Site&& from) noexcept
    : Site() {
    *this = ::std::move(from);
  }

  inline Site& operator=(Site&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Site& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Site* internal_default_instance() {
    return reinterpret_cast<const Site*>(
               &_Site_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Site* other);
  friend void swap(Site& a, Site& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Site* New() const final {
    return CreateMaybeMessage<Site>(nullptr);
  }

  Site* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Site>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Site& from);
  void MergeFrom(const Site& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Site* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 SiteId = 1;
  void clear_siteid();
  static const int kSiteIdFieldNumber = 1;
  ::google::protobuf::int32 siteid() const;
  void set_siteid(::google::protobuf::int32 value);

  // .zl.proto.EContentMap ContentMap = 2;
  void clear_contentmap();
  static const int kContentMapFieldNumber = 2;
  ::zl::proto::EContentMap contentmap() const;
  void set_contentmap(::zl::proto::EContentMap value);

  // @@protoc_insertion_point(class_scope:zl.proto.Site)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 siteid_;
  int contentmap_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Site_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Site

// int32 SiteId = 1;
inline void Site::clear_siteid() {
  siteid_ = 0;
}
inline ::google::protobuf::int32 Site::siteid() const {
  // @@protoc_insertion_point(field_get:zl.proto.Site.SiteId)
  return siteid_;
}
inline void Site::set_siteid(::google::protobuf::int32 value) {
  
  siteid_ = value;
  // @@protoc_insertion_point(field_set:zl.proto.Site.SiteId)
}

// .zl.proto.EContentMap ContentMap = 2;
inline void Site::clear_contentmap() {
  contentmap_ = 0;
}
inline ::zl::proto::EContentMap Site::contentmap() const {
  // @@protoc_insertion_point(field_get:zl.proto.Site.ContentMap)
  return static_cast< ::zl::proto::EContentMap >(contentmap_);
}
inline void Site::set_contentmap(::zl::proto::EContentMap value) {
  
  contentmap_ = value;
  // @@protoc_insertion_point(field_set:zl.proto.Site.ContentMap)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace zl

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_Site_2eproto
