// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: networking/GRPCConnection.proto

#ifndef PROTOBUF_INCLUDED_networking_2fGRPCConnection_2eproto
#define PROTOBUF_INCLUDED_networking_2fGRPCConnection_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "networking/Transmission.pb.h"
#include "networking/NetworkEndPoint.pb.h"
#include <google/protobuf/empty.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_networking_2fGRPCConnection_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_networking_2fGRPCConnection_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_networking_2fGRPCConnection_2eproto();
namespace zl {
namespace proto {
namespace networking {
class ConnectionTransmission;
class ConnectionTransmissionDefaultTypeInternal;
extern ConnectionTransmissionDefaultTypeInternal _ConnectionTransmission_default_instance_;
}  // namespace networking
}  // namespace proto
}  // namespace zl
namespace google {
namespace protobuf {
template<> ::zl::proto::networking::ConnectionTransmission* Arena::CreateMaybeMessage<::zl::proto::networking::ConnectionTransmission>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace zl {
namespace proto {
namespace networking {

// ===================================================================

class ConnectionTransmission final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zl.proto.networking.ConnectionTransmission) */ {
 public:
  ConnectionTransmission();
  virtual ~ConnectionTransmission();

  ConnectionTransmission(const ConnectionTransmission& from);

  inline ConnectionTransmission& operator=(const ConnectionTransmission& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConnectionTransmission(ConnectionTransmission&& from) noexcept
    : ConnectionTransmission() {
    *this = ::std::move(from);
  }

  inline ConnectionTransmission& operator=(ConnectionTransmission&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ConnectionTransmission& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConnectionTransmission* internal_default_instance() {
    return reinterpret_cast<const ConnectionTransmission*>(
               &_ConnectionTransmission_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ConnectionTransmission* other);
  friend void swap(ConnectionTransmission& a, ConnectionTransmission& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConnectionTransmission* New() const final {
    return CreateMaybeMessage<ConnectionTransmission>(nullptr);
  }

  ConnectionTransmission* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ConnectionTransmission>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ConnectionTransmission& from);
  void MergeFrom(const ConnectionTransmission& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConnectionTransmission* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .zl.proto.networking.Transmission Transmission = 1;
  bool has_transmission() const;
  void clear_transmission();
  static const int kTransmissionFieldNumber = 1;
  const ::zl::proto::networking::Transmission& transmission() const;
  ::zl::proto::networking::Transmission* release_transmission();
  ::zl::proto::networking::Transmission* mutable_transmission();
  void set_allocated_transmission(::zl::proto::networking::Transmission* transmission);

  // .zl.proto.networking.NetworkEndPoint ClientListenEndPoint = 2;
  bool has_clientlistenendpoint() const;
  void clear_clientlistenendpoint();
  static const int kClientListenEndPointFieldNumber = 2;
  const ::zl::proto::networking::NetworkEndPoint& clientlistenendpoint() const;
  ::zl::proto::networking::NetworkEndPoint* release_clientlistenendpoint();
  ::zl::proto::networking::NetworkEndPoint* mutable_clientlistenendpoint();
  void set_allocated_clientlistenendpoint(::zl::proto::networking::NetworkEndPoint* clientlistenendpoint);

  // @@protoc_insertion_point(class_scope:zl.proto.networking.ConnectionTransmission)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::zl::proto::networking::Transmission* transmission_;
  ::zl::proto::networking::NetworkEndPoint* clientlistenendpoint_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_networking_2fGRPCConnection_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ConnectionTransmission

// .zl.proto.networking.Transmission Transmission = 1;
inline bool ConnectionTransmission::has_transmission() const {
  return this != internal_default_instance() && transmission_ != nullptr;
}
inline const ::zl::proto::networking::Transmission& ConnectionTransmission::transmission() const {
  const ::zl::proto::networking::Transmission* p = transmission_;
  // @@protoc_insertion_point(field_get:zl.proto.networking.ConnectionTransmission.Transmission)
  return p != nullptr ? *p : *reinterpret_cast<const ::zl::proto::networking::Transmission*>(
      &::zl::proto::networking::_Transmission_default_instance_);
}
inline ::zl::proto::networking::Transmission* ConnectionTransmission::release_transmission() {
  // @@protoc_insertion_point(field_release:zl.proto.networking.ConnectionTransmission.Transmission)
  
  ::zl::proto::networking::Transmission* temp = transmission_;
  transmission_ = nullptr;
  return temp;
}
inline ::zl::proto::networking::Transmission* ConnectionTransmission::mutable_transmission() {
  
  if (transmission_ == nullptr) {
    auto* p = CreateMaybeMessage<::zl::proto::networking::Transmission>(GetArenaNoVirtual());
    transmission_ = p;
  }
  // @@protoc_insertion_point(field_mutable:zl.proto.networking.ConnectionTransmission.Transmission)
  return transmission_;
}
inline void ConnectionTransmission::set_allocated_transmission(::zl::proto::networking::Transmission* transmission) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(transmission_);
  }
  if (transmission) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      transmission = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, transmission, submessage_arena);
    }
    
  } else {
    
  }
  transmission_ = transmission;
  // @@protoc_insertion_point(field_set_allocated:zl.proto.networking.ConnectionTransmission.Transmission)
}

// .zl.proto.networking.NetworkEndPoint ClientListenEndPoint = 2;
inline bool ConnectionTransmission::has_clientlistenendpoint() const {
  return this != internal_default_instance() && clientlistenendpoint_ != nullptr;
}
inline const ::zl::proto::networking::NetworkEndPoint& ConnectionTransmission::clientlistenendpoint() const {
  const ::zl::proto::networking::NetworkEndPoint* p = clientlistenendpoint_;
  // @@protoc_insertion_point(field_get:zl.proto.networking.ConnectionTransmission.ClientListenEndPoint)
  return p != nullptr ? *p : *reinterpret_cast<const ::zl::proto::networking::NetworkEndPoint*>(
      &::zl::proto::networking::_NetworkEndPoint_default_instance_);
}
inline ::zl::proto::networking::NetworkEndPoint* ConnectionTransmission::release_clientlistenendpoint() {
  // @@protoc_insertion_point(field_release:zl.proto.networking.ConnectionTransmission.ClientListenEndPoint)
  
  ::zl::proto::networking::NetworkEndPoint* temp = clientlistenendpoint_;
  clientlistenendpoint_ = nullptr;
  return temp;
}
inline ::zl::proto::networking::NetworkEndPoint* ConnectionTransmission::mutable_clientlistenendpoint() {
  
  if (clientlistenendpoint_ == nullptr) {
    auto* p = CreateMaybeMessage<::zl::proto::networking::NetworkEndPoint>(GetArenaNoVirtual());
    clientlistenendpoint_ = p;
  }
  // @@protoc_insertion_point(field_mutable:zl.proto.networking.ConnectionTransmission.ClientListenEndPoint)
  return clientlistenendpoint_;
}
inline void ConnectionTransmission::set_allocated_clientlistenendpoint(::zl::proto::networking::NetworkEndPoint* clientlistenendpoint) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(clientlistenendpoint_);
  }
  if (clientlistenendpoint) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      clientlistenendpoint = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, clientlistenendpoint, submessage_arena);
    }
    
  } else {
    
  }
  clientlistenendpoint_ = clientlistenendpoint;
  // @@protoc_insertion_point(field_set_allocated:zl.proto.networking.ConnectionTransmission.ClientListenEndPoint)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace networking
}  // namespace proto
}  // namespace zl

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_networking_2fGRPCConnection_2eproto
