// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: launcher/LegacyLauncherService.proto

#ifndef PROTOBUF_INCLUDED_launcher_2fLegacyLauncherService_2eproto
#define PROTOBUF_INCLUDED_launcher_2fLegacyLauncherService_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_launcher_2fLegacyLauncherService_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_launcher_2fLegacyLauncherService_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_launcher_2fLegacyLauncherService_2eproto();
namespace zl {
namespace proto {
namespace launcher {
class ServerDataRequest;
class ServerDataRequestDefaultTypeInternal;
extern ServerDataRequestDefaultTypeInternal _ServerDataRequest_default_instance_;
class ServerDataResponse;
class ServerDataResponseDefaultTypeInternal;
extern ServerDataResponseDefaultTypeInternal _ServerDataResponse_default_instance_;
}  // namespace launcher
}  // namespace proto
}  // namespace zl
namespace google {
namespace protobuf {
template<> ::zl::proto::launcher::ServerDataRequest* Arena::CreateMaybeMessage<::zl::proto::launcher::ServerDataRequest>(Arena*);
template<> ::zl::proto::launcher::ServerDataResponse* Arena::CreateMaybeMessage<::zl::proto::launcher::ServerDataResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace zl {
namespace proto {
namespace launcher {

// ===================================================================

class ServerDataRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zl.proto.launcher.ServerDataRequest) */ {
 public:
  ServerDataRequest();
  virtual ~ServerDataRequest();

  ServerDataRequest(const ServerDataRequest& from);

  inline ServerDataRequest& operator=(const ServerDataRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ServerDataRequest(ServerDataRequest&& from) noexcept
    : ServerDataRequest() {
    *this = ::std::move(from);
  }

  inline ServerDataRequest& operator=(ServerDataRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ServerDataRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServerDataRequest* internal_default_instance() {
    return reinterpret_cast<const ServerDataRequest*>(
               &_ServerDataRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ServerDataRequest* other);
  friend void swap(ServerDataRequest& a, ServerDataRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ServerDataRequest* New() const final {
    return CreateMaybeMessage<ServerDataRequest>(nullptr);
  }

  ServerDataRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ServerDataRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ServerDataRequest& from);
  void MergeFrom(const ServerDataRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerDataRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string MachineName = 1;
  void clear_machinename();
  static const int kMachineNameFieldNumber = 1;
  const ::std::string& machinename() const;
  void set_machinename(const ::std::string& value);
  #if LANG_CXX11
  void set_machinename(::std::string&& value);
  #endif
  void set_machinename(const char* value);
  void set_machinename(const char* value, size_t size);
  ::std::string* mutable_machinename();
  ::std::string* release_machinename();
  void set_allocated_machinename(::std::string* machinename);

  // int32 BackpackStatus = 2;
  void clear_backpackstatus();
  static const int kBackpackStatusFieldNumber = 2;
  ::google::protobuf::int32 backpackstatus() const;
  void set_backpackstatus(::google::protobuf::int32 value);

  // int32 BackpackButtonInput = 3;
  void clear_backpackbuttoninput();
  static const int kBackpackButtonInputFieldNumber = 3;
  ::google::protobuf::int32 backpackbuttoninput() const;
  void set_backpackbuttoninput(::google::protobuf::int32 value);

  // int32 GameSpace = 4;
  void clear_gamespace();
  static const int kGameSpaceFieldNumber = 4;
  ::google::protobuf::int32 gamespace() const;
  void set_gamespace(::google::protobuf::int32 value);

  // int32 AppMode = 5;
  void clear_appmode();
  static const int kAppModeFieldNumber = 5;
  ::google::protobuf::int32 appmode() const;
  void set_appmode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:zl.proto.launcher.ServerDataRequest)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr machinename_;
  ::google::protobuf::int32 backpackstatus_;
  ::google::protobuf::int32 backpackbuttoninput_;
  ::google::protobuf::int32 gamespace_;
  ::google::protobuf::int32 appmode_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_launcher_2fLegacyLauncherService_2eproto;
};
// -------------------------------------------------------------------

class ServerDataResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zl.proto.launcher.ServerDataResponse) */ {
 public:
  ServerDataResponse();
  virtual ~ServerDataResponse();

  ServerDataResponse(const ServerDataResponse& from);

  inline ServerDataResponse& operator=(const ServerDataResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ServerDataResponse(ServerDataResponse&& from) noexcept
    : ServerDataResponse() {
    *this = ::std::move(from);
  }

  inline ServerDataResponse& operator=(ServerDataResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ServerDataResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServerDataResponse* internal_default_instance() {
    return reinterpret_cast<const ServerDataResponse*>(
               &_ServerDataResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ServerDataResponse* other);
  friend void swap(ServerDataResponse& a, ServerDataResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ServerDataResponse* New() const final {
    return CreateMaybeMessage<ServerDataResponse>(nullptr);
  }

  ServerDataResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ServerDataResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ServerDataResponse& from);
  void MergeFrom(const ServerDataResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerDataResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes LegacyServerData = 1;
  void clear_legacyserverdata();
  static const int kLegacyServerDataFieldNumber = 1;
  const ::std::string& legacyserverdata() const;
  void set_legacyserverdata(const ::std::string& value);
  #if LANG_CXX11
  void set_legacyserverdata(::std::string&& value);
  #endif
  void set_legacyserverdata(const char* value);
  void set_legacyserverdata(const void* value, size_t size);
  ::std::string* mutable_legacyserverdata();
  ::std::string* release_legacyserverdata();
  void set_allocated_legacyserverdata(::std::string* legacyserverdata);

  // @@protoc_insertion_point(class_scope:zl.proto.launcher.ServerDataResponse)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr legacyserverdata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_launcher_2fLegacyLauncherService_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ServerDataRequest

// string MachineName = 1;
inline void ServerDataRequest::clear_machinename() {
  machinename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ServerDataRequest::machinename() const {
  // @@protoc_insertion_point(field_get:zl.proto.launcher.ServerDataRequest.MachineName)
  return machinename_.GetNoArena();
}
inline void ServerDataRequest::set_machinename(const ::std::string& value) {
  
  machinename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zl.proto.launcher.ServerDataRequest.MachineName)
}
#if LANG_CXX11
inline void ServerDataRequest::set_machinename(::std::string&& value) {
  
  machinename_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zl.proto.launcher.ServerDataRequest.MachineName)
}
#endif
inline void ServerDataRequest::set_machinename(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  machinename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zl.proto.launcher.ServerDataRequest.MachineName)
}
inline void ServerDataRequest::set_machinename(const char* value, size_t size) {
  
  machinename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zl.proto.launcher.ServerDataRequest.MachineName)
}
inline ::std::string* ServerDataRequest::mutable_machinename() {
  
  // @@protoc_insertion_point(field_mutable:zl.proto.launcher.ServerDataRequest.MachineName)
  return machinename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ServerDataRequest::release_machinename() {
  // @@protoc_insertion_point(field_release:zl.proto.launcher.ServerDataRequest.MachineName)
  
  return machinename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ServerDataRequest::set_allocated_machinename(::std::string* machinename) {
  if (machinename != nullptr) {
    
  } else {
    
  }
  machinename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), machinename);
  // @@protoc_insertion_point(field_set_allocated:zl.proto.launcher.ServerDataRequest.MachineName)
}

// int32 BackpackStatus = 2;
inline void ServerDataRequest::clear_backpackstatus() {
  backpackstatus_ = 0;
}
inline ::google::protobuf::int32 ServerDataRequest::backpackstatus() const {
  // @@protoc_insertion_point(field_get:zl.proto.launcher.ServerDataRequest.BackpackStatus)
  return backpackstatus_;
}
inline void ServerDataRequest::set_backpackstatus(::google::protobuf::int32 value) {
  
  backpackstatus_ = value;
  // @@protoc_insertion_point(field_set:zl.proto.launcher.ServerDataRequest.BackpackStatus)
}

// int32 BackpackButtonInput = 3;
inline void ServerDataRequest::clear_backpackbuttoninput() {
  backpackbuttoninput_ = 0;
}
inline ::google::protobuf::int32 ServerDataRequest::backpackbuttoninput() const {
  // @@protoc_insertion_point(field_get:zl.proto.launcher.ServerDataRequest.BackpackButtonInput)
  return backpackbuttoninput_;
}
inline void ServerDataRequest::set_backpackbuttoninput(::google::protobuf::int32 value) {
  
  backpackbuttoninput_ = value;
  // @@protoc_insertion_point(field_set:zl.proto.launcher.ServerDataRequest.BackpackButtonInput)
}

// int32 GameSpace = 4;
inline void ServerDataRequest::clear_gamespace() {
  gamespace_ = 0;
}
inline ::google::protobuf::int32 ServerDataRequest::gamespace() const {
  // @@protoc_insertion_point(field_get:zl.proto.launcher.ServerDataRequest.GameSpace)
  return gamespace_;
}
inline void ServerDataRequest::set_gamespace(::google::protobuf::int32 value) {
  
  gamespace_ = value;
  // @@protoc_insertion_point(field_set:zl.proto.launcher.ServerDataRequest.GameSpace)
}

// int32 AppMode = 5;
inline void ServerDataRequest::clear_appmode() {
  appmode_ = 0;
}
inline ::google::protobuf::int32 ServerDataRequest::appmode() const {
  // @@protoc_insertion_point(field_get:zl.proto.launcher.ServerDataRequest.AppMode)
  return appmode_;
}
inline void ServerDataRequest::set_appmode(::google::protobuf::int32 value) {
  
  appmode_ = value;
  // @@protoc_insertion_point(field_set:zl.proto.launcher.ServerDataRequest.AppMode)
}

// -------------------------------------------------------------------

// ServerDataResponse

// bytes LegacyServerData = 1;
inline void ServerDataResponse::clear_legacyserverdata() {
  legacyserverdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ServerDataResponse::legacyserverdata() const {
  // @@protoc_insertion_point(field_get:zl.proto.launcher.ServerDataResponse.LegacyServerData)
  return legacyserverdata_.GetNoArena();
}
inline void ServerDataResponse::set_legacyserverdata(const ::std::string& value) {
  
  legacyserverdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zl.proto.launcher.ServerDataResponse.LegacyServerData)
}
#if LANG_CXX11
inline void ServerDataResponse::set_legacyserverdata(::std::string&& value) {
  
  legacyserverdata_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zl.proto.launcher.ServerDataResponse.LegacyServerData)
}
#endif
inline void ServerDataResponse::set_legacyserverdata(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  legacyserverdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zl.proto.launcher.ServerDataResponse.LegacyServerData)
}
inline void ServerDataResponse::set_legacyserverdata(const void* value, size_t size) {
  
  legacyserverdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zl.proto.launcher.ServerDataResponse.LegacyServerData)
}
inline ::std::string* ServerDataResponse::mutable_legacyserverdata() {
  
  // @@protoc_insertion_point(field_mutable:zl.proto.launcher.ServerDataResponse.LegacyServerData)
  return legacyserverdata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ServerDataResponse::release_legacyserverdata() {
  // @@protoc_insertion_point(field_release:zl.proto.launcher.ServerDataResponse.LegacyServerData)
  
  return legacyserverdata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ServerDataResponse::set_allocated_legacyserverdata(::std::string* legacyserverdata) {
  if (legacyserverdata != nullptr) {
    
  } else {
    
  }
  legacyserverdata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), legacyserverdata);
  // @@protoc_insertion_point(field_set_allocated:zl.proto.launcher.ServerDataResponse.LegacyServerData)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace launcher
}  // namespace proto
}  // namespace zl

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_launcher_2fLegacyLauncherService_2eproto
